# Generated by Django 5.1.4 on 2026-04-10 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph_rag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('platform_type', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('custom', 'Custom')], default='', max_length=20)),
                ('layout_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contents_layout_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'contents_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contents.category')),
            ],
            options={
                'db_table': 'contents_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('platform_type', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Chờ Review'), ('approved', 'Đã Duyệt'), ('scheduled', 'Đã Lên Lịch'), ('published', 'Đã Đăng'), ('archived', 'Lưu Trữ')], db_index=True, default='draft', max_length=20)),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='contents.category')),
                ('rag_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_posts', to='graph_rag.raginstance')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='contents.tag')),
            ],
            options={
                'db_table': 'contents_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContentGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('generation_type', models.CharField(choices=[('full_post', 'Full Post'), ('hashtags', 'Hashtags'), ('summary', 'Summary'), ('caption', 'Caption'), ('translation', 'Translation'), ('improvement', 'Improvement'), ('ab_variant', 'A/B Variant')], max_length=20)),
                ('prompt', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('result_content', models.TextField(blank=True, default='')),
                ('result_variants', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_generations', to=settings.AUTH_USER_MODEL)),
                ('rag_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_generations', to='graph_rag.raginstance')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='contents.post')),
            ],
            options={
                'db_table': 'contents_ai_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.post')),
            ],
            options={
                'db_table': 'contents_post_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='contents/media/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='contents.post')),
            ],
            options={
                'db_table': 'contents_post_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('platform_type', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('custom', 'Custom')], max_length=20)),
                ('content_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='contents.category')),
            ],
            options={
                'db_table': 'contents_post_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('variant_index', models.PositiveSmallIntegerField(default=1)),
                ('layout_json', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_banner_layouts', to=settings.AUTH_USER_MODEL)),
                ('rag_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_layouts', to='graph_rag.raginstance')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_layouts', to='contents.post')),
            ],
            options={
                'db_table': 'contents_banner_layouts',
                'ordering': ['variant_index'],
                'unique_together': {('post', 'variant_index')},
            },
        ),
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_versions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contents.post')),
            ],
            options={
                'db_table': 'contents_post_versions',
                'ordering': ['-version_number'],
                'unique_together': {('post', 'version_number')},
            },
        ),
    ]
