# Generated by Django 5.1.4 on 2026-04-10 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('platform_type', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('webhook_url', models.URLField(help_text='URL của nền tảng để nhận bài viết khi đến lịch đăng.')),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret key dùng để ký HMAC outgoing webhook.', max_length=500)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unreachable', 'Unreachable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platforms_platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('endpoint_url', models.URLField(help_text='URL nhận callback từ nền tảng (incoming).')),
                ('event_types', models.JSONField(default=list)),
                ('secret_key', models.CharField(help_text='Secret key để verify HMAC signature của incoming webhook.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='platforms.platform')),
            ],
            options={
                'db_table': 'platforms_webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], db_index=True, max_length=10)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('schedule_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='platforms.platform')),
            ],
            options={
                'db_table': 'platforms_webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'created_at'], name='platforms_w_platfor_d9f322_idx'), models.Index(fields=['direction', 'created_at'], name='platforms_w_directi_0e65f4_idx')],
            },
        ),
    ]
