from django.urls import path
from apps.graph_rag.views import (
    RAGInstanceListCreateView,
    RAGInstanceDetailView,
    RAGInstanceConfigView,
    RAGInstanceCloneView,
    RAGInstanceKBView,
    RAGInstanceSkillView,
    KnowledgeBaseListCreateView,
    KnowledgeBaseDetailView,
    DocumentListView,
    DocumentUploadView,
    DocumentTextView,
    DocumentURLView,
    DocumentDetailView,
    DocumentChunkListView,
    KnowledgeBaseGraphBuildView,
    ChatQueryView,
    ConversationListView,
    ConversationDetailView,
    MessageFeedbackView,
    AccessPermissionListCreateView,
    AccessPermissionDeleteView,
    MyAccessView,
    InstanceAnalyticsView,
    UsageLogListView,
    ConfigHistoryListView,
)

app_name = "graph_rag"

urlpatterns = [
    # ── RAG Instances ───────────────────────────────
    path(
        "instances/",
        RAGInstanceListCreateView.as_view(),
        name="instance-list",
    ),
    path(
        "instances/<slug:slug>/",
        RAGInstanceDetailView.as_view(),
        name="instance-detail",
    ),
    path(
        "instances/<slug:slug>/config/",
        RAGInstanceConfigView.as_view(),
        name="instance-config",
    ),
    path(
        "instances/<slug:slug>/clone/",
        RAGInstanceCloneView.as_view(),
        name="instance-clone",
    ),
    path(
        "instances/<slug:slug>/knowledge-bases/",
        RAGInstanceKBView.as_view(),
        name="instance-kb",
    ),
    path(
        "instances/<slug:slug>/skills/",
        RAGInstanceSkillView.as_view(),
        name="instance-skills",
    ),
    # ── Knowledge Bases ─────────────────────────────
    path(
        "knowledge-bases/",
        KnowledgeBaseListCreateView.as_view(),
        name="kb-list",
    ),
    path(
        "knowledge-bases/<slug:slug>/",
        KnowledgeBaseDetailView.as_view(),
        name="kb-detail",
    ),
    path(
        "knowledge-bases/<slug:slug>/documents/",
        DocumentListView.as_view(),
        name="doc-list",
    ),
    path(
        "knowledge-bases/<slug:slug>/documents/upload/",
        DocumentUploadView.as_view(),
        name="doc-upload",
    ),
    path(
        "knowledge-bases/<slug:slug>/documents/text/",
        DocumentTextView.as_view(),
        name="doc-text",
    ),
    path(
        "knowledge-bases/<slug:slug>/documents/url/",
        DocumentURLView.as_view(),
        name="doc-url",
    ),
    path(
        "knowledge-bases/<slug:slug>/graph/build/",
        KnowledgeBaseGraphBuildView.as_view(),
        name="kb-graph-build",
    ),
    # ── Documents ───────────────────────────────────
    path(
        "documents/<uuid:pk>/",
        DocumentDetailView.as_view(),
        name="doc-detail",
    ),
    path(
        "documents/<uuid:pk>/chunks/",
        DocumentChunkListView.as_view(),
        name="doc-chunks",
    ),
    # ── Chat ────────────────────────────────────────
    path(
        "instances/<slug:slug>/chat/",
        ChatQueryView.as_view(),
        name="chat-query",
    ),
    path(
        "instances/<slug:slug>/conversations/",
        ConversationListView.as_view(),
        name="conversation-list",
    ),
    path(
        "instances/<slug:slug>/conversations/<uuid:conversation_id>/",
        ConversationDetailView.as_view(),
        name="conversation-detail",
    ),
    path(
        "messages/<uuid:message_id>/feedback/",
        MessageFeedbackView.as_view(),
        name="message-feedback",
    ),
    # ── Access ──────────────────────────────────────
    path(
        "instances/<slug:slug>/access/",
        AccessPermissionListCreateView.as_view(),
        name="access-list",
    ),
    path(
        "instances/<slug:slug>/access/<uuid:pk>/",
        AccessPermissionDeleteView.as_view(),
        name="access-delete",
    ),
    path(
        "instances/<slug:slug>/my-access/",
        MyAccessView.as_view(),
        name="my-access",
    ),
    # ── Analytics ───────────────────────────────────
    path(
        "instances/<slug:slug>/analytics/",
        InstanceAnalyticsView.as_view(),
        name="instance-analytics",
    ),
    path(
        "instances/<slug:slug>/usage-logs/",
        UsageLogListView.as_view(),
        name="usage-logs",
    ),
    path(
        "instances/<slug:slug>/config-history/",
        ConfigHistoryListView.as_view(),
        name="config-history",
    ),
]
