# Generated by Django 5.1.4 on 2026-04-10 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ Đăng'), ('processing', 'Đang Xử Lý'), ('published', 'Đã Đăng'), ('failed', 'Thất Bại'), ('cancelled', 'Đã Hủy')], db_index=True, default='pending', max_length=20)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='platforms.platform')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contents.post')),
            ],
            options={
                'db_table': 'scheduling_post_schedules',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scheduling.postschedule')),
            ],
            options={
                'db_table': 'scheduling_publish_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postschedule',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduling__status_f28246_idx'),
        ),
    ]
